POST http://localhost:4000/api/auth/register
Content-Type: application/json 

{
    "email":"rave@gmail.com",
    "password":"111",
    "role":"Technician"
}

###
POST http://localhost:4000/api/auth/login
Content-Type: application/json 

{
    "email":"rave@gmail.com",
    "password":"111"
    
}